


insert into Address (city, country, postal_code, state, street) values ('Kolsko', 'Poland', '67-415', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '15411 Florence Plaza');
insert into Address (city, country, postal_code, state, street) values ('Herrera', 'Argentina', '4326', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '533 Pierstorff Court');
insert into Address (city, country, postal_code, state, street) values ('Monte da Pedra', 'Portugal', '7430-315', 'Portalegre', '69441 Kedzie Avenue');
insert into Address (city, country, postal_code, state, street) values ('Fengting', 'China', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '43993 Ronald Regan Avenue');
insert into Address (city, country, postal_code, state, street) values ('Bronx', 'United States', '10469', 'New York', '60001 Lyons Junction');
insert into Address (city, country, postal_code, state, street) values ('Ruihong', 'China', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '58 Garrison Drive');
insert into Address (city, country, postal_code, state, street) values ('Pereiros', 'Portugal', '3040-723', 'Coimbra', '24 Toban Alley');
insert into Address (city, country, postal_code, state, street) values ('Usevia', 'Tanzania', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '841 Dixon Parkway');
insert into Address (city, country, postal_code, state, street) values ('San José Acatempa', 'Guatemala', '22016', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '2 Southridge Center');
insert into Address (city, country, postal_code, state, street) values ('Qal‘ah-ye Shāhī', 'Afghanistan', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '08557 Welch Junction');
insert into Address (city, country, postal_code, state, street) values ('Pérez', 'Argentina', '2121', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '6316 Longview Street');
insert into Address (city, country, postal_code, state, street) values ('Fílla', 'Greece', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '0048 Eastlawn Terrace');
insert into Address (city, country, postal_code, state, street) values ('Kenitra', 'Morocco', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '5 Katie Avenue');
insert into Address (city, country, postal_code, state, street) values ('Trâu Quỳ', 'Vietnam', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '0 Sundown Terrace');
insert into Address (city, country, postal_code, state, street) values ('Chatuchak', 'Thailand', '64180', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '96497 Almo Parkway');
insert into Address (city, country, postal_code, state, street) values ('Chinju', 'South Korea', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '7688 Colorado Parkway');
insert into Address (city, country, postal_code, state, street) values ('Bazi', 'China', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '52585 Maple Road');
insert into Address (city, country, postal_code, state, street) values ('Choa Saidān Shāh', 'Pakistan', '53401', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '06 Dayton Junction');
insert into Address (city, country, postal_code, state, street) values ('Święciechowa', 'Poland', '64-115', 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', '700 Stang Road');
insert into Address (city, country, postal_code, state, street) values ('Järfälla', 'Sweden', '175 61', 'Stockholm', '97366 Service Junction');



INSERT INTO Client (addressid,date_of_birth,document,email,login,name,passwd,phone)
VALUES
   (8,'1978-11-11 20:05:21','480.851.866-40','magna.phasellus@protonmail.org','Hyde','Jillian Wallace','QYL12MOJ4CQ','(971) 581-3177'),
  (14,'1977-06-04 23:01:18','621.967.785-66','laoreet.posuere.enim@outlook.edu','Garner','Jacob Reynolds','XLU36HJH9PP','1-483-247-2677'),
  (17,'1988-06-19 19:01:45','932.656.693-48','dictum.eu.placerat@protonmail.couk','Best','Dorothy Sellers','YPU62GDE4NE','(857) 867-5312'),
  (7,'1992-01-31 10:11:51','252.834.564-87','justo.sit@protonmail.org','Griffith','Oren Castaneda','JFX27NXR9KV','(772) 150-4517'),
  (16,'1995-05-27 03:56:17','148.097.717-62','eget.metus@outlook.com','Matthews','Brett Barnett','FHH70OKP6GZ','1-836-614-2381'),
  (11,'1975-09-17 14:15:41','809.122.888-35','nam.tempor@icloud.org','Slater','Ginger Newman','JTX66IVF6YM','(503) 727-2442'),
  (6,'1947-01-27 07:41:21','537.258.271-77','sodales@icloud.edu','Swanson','Katelyn Ortega','SNZ67QCT7TR','1-834-922-3183'),
  (5,'1968-12-16 02:17:57','132.682.775-87','sed.dolor.fusce@icloud.edu','Roman','Julian Nicholson','WRA34FIL4XC','1-941-556-6664'),
  (3,'1945-02-04 03:07:14','462.673.076-54','lorem.semper.auctor@yahoo.org','Cohen','Keiko Woodard','NHD67JML6BG','1-356-417-1176'),
  (3,'1998-03-06 06:29:59','484.836.208-72','pede.sagittis.augue@hotmail.net','Mendoza','Tamekah Schneider','THF27FXB0EV','1-254-277-5837'),
  (8,'1971-10-31 11:28:58','662.713.323-55','rutrum.eu.ultrices@google.edu','Morse','Axel Osborn','NON47QGT4UX','(961) 761-3046'),
  (17,'1962-05-10 18:37:37','761.704.668-14','tellus.phasellus@aol.ca','Kaufman','Hayden Sanders','YMS22BYW4KL','1-515-626-8124'),
  (1,'1952-02-16 11:12:24','605.143.536-26','cursus@hotmail.edu','Love','Arsenio Rich','XUD63NIJ2QX','1-655-338-6598'),
  (3,'2008-11-15 13:49:16','725.889.681-42','pulvinar.arcu@yahoo.edu','Hopkins','Carson Ray','XJI43SSY1YN','1-616-202-7858'),
  (4,'1988-03-26 04:56:57','147.250.212-32','non.justo@aol.ca','Ashley','Astra Mcfarland','OMF58LBK3IO','1-232-614-1691'),
  (3,'1958-10-07 15:41:25','578.848.674-68','ac.fermentum@icloud.com','Rich','Vivian Fernandez','ANC28IIB2KV','(745) 263-4181'),
  (14,'1991-11-10 23:20:43','575.834.111-52','cum.sociis@icloud.com','Bowen','Gil Ball','MXJ86OTY2SL','(224) 237-3189'),
  (13,'1964-04-23 03:30:10','979.144.858-13','sem.pellentesque.ut@protonmail.ca','Noel','Hyatt Elliott','MAD73GWP0HS','(175) 844-5612'),
  (7,'2022-03-02 22:50:52','350.144.679-14','leo.cras.vehicula@hotmail.com','Sweeney','Randall Howell','YNR58DFF7CQ','1-264-854-3244'),
  (17,'1969-12-11 12:54:01','457.012.547-20','tempor@yahoo.edu','Vazquez','Basia Santana','QZO75CXY6NF','(566) 674-0758');



  INSERT INTO Owner(addressid,date_of_birth,document,email,login,name,passwd,phone)
VALUES
	(15,'1967-07-31 18:56:48','647.643.122-35','nulla.eu@aol.org','Vinson','Harper Atkins','PXE84RBA1BK','(593) 675-7116'),
  (18,'1950-02-05 22:28:40','067.111.871-86','libero@aol.edu','Ruiz','Berk Soto','QJE80THL8CW','(886) 265-4465'),
  (15,'1987-08-17 08:48:23','871.088.958-27','mollis.vitae@hotmail.edu','Rosa','Patrick Holder','GPQ04CSE4WU','1-348-262-3635'),
  (3,'2016-07-09 00:20:15','194.000.796-15','elit.elit.fermentum@aol.couk','Sellers','May Green','JCL88GJN6UT','1-829-438-9456'),
  (15,'1979-09-14 02:13:32','688.467.781-47','vitae.aliquet@icloud.couk','York','Beatrice Wilkins','JRE68EZH5CS','1-336-350-7613'),
  (13,'2021-03-29 18:36:30','371.396.761-28','vulputate.velit@outlook.org','Mcdowell','Rebekah Glass','COM38TXO8GJ','(448) 648-7574'),
  (3,'2007-08-22 23:02:15','595.063.200-94','dolor.sit@outlook.com','Campos','Jerome Lane','WLN41JTO4JJ','(204) 322-2224'),
  (11,'1986-12-06 02:04:22','267.541.419-86','mauris@icloud.ca','Reed','Tad Dixon','QPM58DJB4XU','(436) 732-3075'),
  (8,'2022-11-12 00:55:40','712.928.559-36','velit@protonmail.net','Collier','Arden Heath','OBY73NWP4XH','1-875-104-6645'),
  (4,'1976-01-15 20:25:10','284.771.611-33','interdum@aol.net','Acevedo','Charde Coffey','PKW87BJI4QL','1-428-315-1532'),
  (10,'2000-08-19 23:30:40','383.094.123-31','ante.bibendum@protonmail.net','Black','Mechelle Carson','DIV04RWE2KD','1-323-247-6223'),
  (15,'1955-05-01 06:19:50','515.233.671-68','penatibus.et@google.net','Haynes','Jessamine English','KQO59UOE8TP','1-890-356-3294'),
  (3,'1964-08-07 18:21:20','053.491.435-13','eu.erat@aol.couk','Daniels','Aidan Franco','FIY71XIX8QD','(872) 636-5785'),
  (3,'1946-04-24 20:11:30','018.216.533-87','imperdiet.non@aol.net','Ratliff','Valentine Carney','GRT70MRA8XB','1-724-561-3489'),
  (2,'1959-10-16 08:27:56','874.706.978-84','malesuada.augue@yahoo.net','Alvarez','Kylie Tran','IGC05UHF4LL','1-249-576-6798'),
  (16,'1966-02-02 21:28:26','854.442.241-37','tellus@google.ca','Weber','Thomas Buckner','PIE24VAB2HL','(718) 272-5627'),
  (9,'1966-11-12 06:38:34','369.791.875-69','lorem.lorem.luctus@aol.com','Sosa','Felicia Fry','TDB27ONC4FT','1-319-146-0865'),
  (1,'1995-06-11 12:07:04','297.112.703-50','lacinia.vitae@icloud.couk','Mosley','Kasimir Reed','RCX16LNQ4KR','(376) 376-2233'),
  (12,'2008-09-30 16:50:27','774.678.044-85','odio.nam@hotmail.org','Kidd','Carlos Whitley','FPR23MTO0BK','1-781-817-8235'),
  (19,'1974-12-28 20:55:17','931.661.881-37','massa.quisque@outlook.ca','Mitchell','Uriah Martin','OEY02BHX7ED','1-801-216-7163');

INSERT INTO Store(CNPJ,name,ownerid)
VALUES
  ('30.555.633/7880-84','Cras Lorem PC',6),
  ('35.741.686/6986-51','Purus Inc.',16),
  ('30.185.319/6531-77','Dolor Associates',2),
  ('62.388.576/5472-66','Vitae Erat Corporation',13),
  ('91.689.787/4147-21','Luctus Curabitur Foundation',14),
  ('81.433.646/3757-07','Molestie Pharetra Inc.',19),
  ('31.088.251/6504-21','Quisque Purus Incorporated',19),
  ('05.385.271/8434-42','Eget Varius Incorporated',8),
  ('71.270.547/3035-60','Ut LLC',17),
  ('58.813.922/7305-78','Tempor Est Industries',3),
  ('91.951.527/6268-42','Massa Quisque Porttitor Associates',11),
  ('13.966.332/6462-67','Dui Nec PC',1),
  ('94.841.821/2277-35','Pharetra Quisque Limited',17),
  ('36.766.612/1756-81','Semper Nam Tempor Corporation',12),
  ('53.836.513/4780-74','Metus Sit Inc.',2),
  ('02.385.634/2681-35','Rutrum Eu Ultrices LLP',17),
  ('40.471.607/6753-48','Aliquam Arcu Aliquam LLC',18),
  ('89.551.726/7252-74','Ipsum Limited',2),
  ('47.241.061/5949-68','Interdum Sed Ltd',10),
  ('04.637.852/2838-58','Libero Et Tristique Limited',19);


  insert into Product (bar_code, description, image, name) values (56415, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/179x100.png/5fa2dd/ffffff', 'Flour - Whole Wheat');
insert into Product (bar_code, description, image, name) values (61903, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/190x100.png/5fa2dd/ffffff', 'Vinegar - White');
insert into Product (bar_code, description, image, name) values (93067, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/106x100.png/5fa2dd/ffffff', 'Snapple Raspberry Tea');
insert into Product (bar_code, description, image, name) values (59508, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/213x100.png/cc0000/ffffff', 'Wine - Alsace Riesling Reserve');
insert into Product (bar_code, description, image, name) values (85215, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/178x100.png/dddddd/000000', 'Flour - Corn, Fine');
insert into Product (bar_code, description, image, name) values (98895, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/229x100.png/cc0000/ffffff', 'Yoghurt Tubes');
insert into Product (bar_code, description, image, name) values (46372, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/211x100.png/dddddd/000000', 'Breadfruit');
insert into Product (bar_code, description, image, name) values (56156, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/189x100.png/ff4444/ffffff', 'Muffin - Zero Transfat');
insert into Product (bar_code, description, image, name) values (40710, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/182x100.png/5fa2dd/ffffff', 'Chocolate - Dark Callets');
insert into Product (bar_code, description, image, name) values (75979, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/232x100.png/ff4444/ffffff', 'Wine - Gewurztraminer Pierre');
insert into Product (bar_code, description, image, name) values (55742, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/216x100.png/dddddd/000000', 'Ecolab Crystal Fusion');
insert into Product (bar_code, description, image, name) values (77732, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/162x100.png/5fa2dd/ffffff', 'Oil - Cooking Spray');
insert into Product (bar_code, description, image, name) values (67672, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/198x100.png/dddddd/000000', 'Cranberries - Fresh');
insert into Product (bar_code, description, image, name) values (63497, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/166x100.png/5fa2dd/ffffff', 'Wine - Cahors Ac 2000, Clos');
insert into Product (bar_code, description, image, name) values (90812, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/221x100.png/dddddd/000000', 'Cheese - Grana Padano');
insert into Product (bar_code, description, image, name) values (63563, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/143x100.png/cc0000/ffffff', 'Chutney Sauce - Mango');
insert into Product (bar_code, description, image, name) values (78805, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/202x100.png/5fa2dd/ffffff', 'Wine - Blue Nun Qualitatswein');
insert into Product (bar_code, description, image, name) values (47232, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/225x100.png/dddddd/000000', 'Cheese - Grana Padano');
insert into Product (bar_code, description, image, name) values (43960, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/173x100.png/dddddd/000000', 'Foil - Round Foil');
insert into Product (bar_code, description, image, name) values (99879, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'Beef - Ground Medium');
insert into Product (bar_code, description, image, name) values (74860, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/169x100.png/5fa2dd/ffffff', 'Bread - Crusty Italian Poly');
insert into Product (bar_code, description, image, name) values (46868, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/104x100.png/cc0000/ffffff', 'Bread Base - Goodhearth');
insert into Product (bar_code, description, image, name) values (55492, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/151x100.png/5fa2dd/ffffff', 'Wine - Merlot Vina Carmen');
insert into Product (bar_code, description, image, name) values (61861, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/128x100.png/5fa2dd/ffffff', 'Syrup - Golden, Lyles');
insert into Product (bar_code, description, image, name) values (47493, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/196x100.png/dddddd/000000', 'Split Peas - Yellow, Dry');
insert into Product (bar_code, description, image, name) values (82963, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/128x100.png/dddddd/000000', 'Beer - Alexander Kieths, Pale Ale');
insert into Product (bar_code, description, image, name) values (74750, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/200x100.png/5fa2dd/ffffff', 'Steampan - Lid For Half Size');
insert into Product (bar_code, description, image, name) values (65878, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/236x100.png/ff4444/ffffff', 'Gin - Gilbeys London, Dry');
insert into Product (bar_code, description, image, name) values (72986, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/224x100.png/5fa2dd/ffffff', 'Coffee Cup 16oz Foam');
insert into Product (bar_code, description, image, name) values (59015, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/136x100.png/5fa2dd/ffffff', 'Soup - Campbells Mac N Cheese');
insert into Product (bar_code, description, image, name) values (75994, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/207x100.png/ff4444/ffffff', 'Wheat - Soft Kernal Of Wheat');
insert into Product (bar_code, description, image, name) values (96824, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/226x100.png/5fa2dd/ffffff', 'Chocolate - Milk');
insert into Product (bar_code, description, image, name) values (72450, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/137x100.png/cc0000/ffffff', 'Cake - Cake Sheet Macaroon');
insert into Product (bar_code, description, image, name) values (72325, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/181x100.png/5fa2dd/ffffff', 'Tea - Honey Green Tea');
insert into Product (bar_code, description, image, name) values (79534, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/169x100.png/5fa2dd/ffffff', 'Wine - Cotes Du Rhone');
insert into Product (bar_code, description, image, name) values (94281, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/146x100.png/dddddd/000000', 'Ice - Clear, 300 Lb For Carving');
insert into Product (bar_code, description, image, name) values (57055, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/125x100.png/dddddd/000000', 'Dasheen');
insert into Product (bar_code, description, image, name) values (54526, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/194x100.png/dddddd/000000', 'Puree - Mocha');
insert into Product (bar_code, description, image, name) values (95503, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/110x100.png/cc0000/ffffff', 'Teriyaki Sauce');
insert into Product (bar_code, description, image, name) values (60392, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/246x100.png/dddddd/000000', 'Allspice - Jamaican');
insert into Product (bar_code, description, image, name) values (66880, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/176x100.png/dddddd/000000', 'Salmon Steak - Cohoe 6 Oz');
insert into Product (bar_code, description, image, name) values (75119, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/130x100.png/dddddd/000000', 'Tea - Herbal - 6 Asst');
insert into Product (bar_code, description, image, name) values (51358, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/115x100.png/ff4444/ffffff', 'Shiratamako - Rice Flour');
insert into Product (bar_code, description, image, name) values (77428, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/181x100.png/ff4444/ffffff', 'Wine - Chateau Aqueria Tavel');
insert into Product (bar_code, description, image, name) values (74030, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/185x100.png/5fa2dd/ffffff', 'Tea - Mint');
insert into Product (bar_code, description, image, name) values (84867, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/111x100.png/dddddd/000000', 'Syrup - Monin, Swiss Choclate');
insert into Product (bar_code, description, image, name) values (74076, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/230x100.png/cc0000/ffffff', 'Lamb - Loin Chops');
insert into Product (bar_code, description, image, name) values (48353, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/141x100.png/5fa2dd/ffffff', 'Veal - Kidney');
insert into Product (bar_code, description, image, name) values (41116, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/242x100.png/cc0000/ffffff', 'Lettuce - Frisee');
insert into Product (bar_code, description, image, name) values (57503, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/244x100.png/ff4444/ffffff', 'Star Anise, Whole');
insert into Product (bar_code, description, image, name) values (93729, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/148x100.png/ff4444/ffffff', 'Chinese Foods - Chicken Wing');
insert into Product (bar_code, description, image, name) values (79862, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/138x100.png/dddddd/000000', 'Stock - Chicken, White');
insert into Product (bar_code, description, image, name) values (89089, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/230x100.png/5fa2dd/ffffff', 'Goldschalger');
insert into Product (bar_code, description, image, name) values (95928, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/229x100.png/5fa2dd/ffffff', 'Wine - Marlbourough Sauv Blanc');
insert into Product (bar_code, description, image, name) values (66332, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/204x100.png/5fa2dd/ffffff', 'Wine - Jackson Triggs Okonagan');
insert into Product (bar_code, description, image, name) values (41917, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/214x100.png/dddddd/000000', 'Cookie Dough - Chocolate Chip');
insert into Product (bar_code, description, image, name) values (67428, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/226x100.png/5fa2dd/ffffff', 'Vinegar - White');
insert into Product (bar_code, description, image, name) values (44982, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/234x100.png/ff4444/ffffff', 'Shrimp - Black Tiger 6 - 8');
insert into Product (bar_code, description, image, name) values (46021, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/127x100.png/dddddd/000000', 'Nacho Chips');
insert into Product (bar_code, description, image, name) values (85679, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/164x100.png/cc0000/ffffff', 'Bread - Rolls, Corn');
insert into Product (bar_code, description, image, name) values (94940, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/170x100.png/dddddd/000000', 'Cookie Dough - Peanut Butter');
insert into Product (bar_code, description, image, name) values (49906, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/187x100.png/5fa2dd/ffffff', 'Bag - Bread, White, Plain');
insert into Product (bar_code, description, image, name) values (60687, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/233x100.png/dddddd/000000', 'Kiwi Gold Zespri');
insert into Product (bar_code, description, image, name) values (81354, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/216x100.png/dddddd/000000', 'Pepper - Red Chili');
insert into Product (bar_code, description, image, name) values (59033, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/172x100.png/ff4444/ffffff', 'Ice Cream Bar - Rolo Cone');
insert into Product (bar_code, description, image, name) values (47555, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/250x100.png/cc0000/ffffff', 'Corn - Mini');
insert into Product (bar_code, description, image, name) values (54493, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/237x100.png/ff4444/ffffff', 'Pear - Halves');
insert into Product (bar_code, description, image, name) values (87358, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/225x100.png/ff4444/ffffff', 'Irish Cream - Baileys');
insert into Product (bar_code, description, image, name) values (75348, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/114x100.png/ff4444/ffffff', 'Wine - Two Oceans Cabernet');
insert into Product (bar_code, description, image, name) values (84102, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/169x100.png/ff4444/ffffff', 'Cake - Sheet Strawberry');
insert into Product (bar_code, description, image, name) values (51261, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/207x100.png/5fa2dd/ffffff', 'Cookies - Amaretto');
insert into Product (bar_code, description, image, name) values (71815, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/222x100.png/cc0000/ffffff', 'Wine - Dubouef Macon - Villages');
insert into Product (bar_code, description, image, name) values (76594, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/248x100.png/5fa2dd/ffffff', 'Juice - Pineapple, 341 Ml');
insert into Product (bar_code, description, image, name) values (78633, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/197x100.png/5fa2dd/ffffff', 'Soup - Cream Of Broccoli, Dry');
insert into Product (bar_code, description, image, name) values (83554, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/164x100.png/5fa2dd/ffffff', 'Broom Handle');
insert into Product (bar_code, description, image, name) values (45483, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/182x100.png/cc0000/ffffff', 'Raspberries - Fresh');
insert into Product (bar_code, description, image, name) values (79709, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/233x100.png/5fa2dd/ffffff', 'Water - Spring 1.5lit');
insert into Product (bar_code, description, image, name) values (59133, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/126x100.png/cc0000/ffffff', 'Cardamon Seed / Pod');
insert into Product (bar_code, description, image, name) values (62621, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/226x100.png/ff4444/ffffff', 'Pasta - Lasagna, Dry');
insert into Product (bar_code, description, image, name) values (78781, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/117x100.png/dddddd/000000', 'Cut Wakame - Hanawakaba');
insert into Product (bar_code, description, image, name) values (71691, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/139x100.png/dddddd/000000', 'Chick Peas - Canned');
insert into Product (bar_code, description, image, name) values (90929, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/248x100.png/5fa2dd/ffffff', 'Extract - Lemon');
insert into Product (bar_code, description, image, name) values (70487, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/155x100.png/ff4444/ffffff', 'Vinegar - Champagne');
insert into Product (bar_code, description, image, name) values (90720, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/154x100.png/5fa2dd/ffffff', 'Sugar - Brown');
insert into Product (bar_code, description, image, name) values (41078, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/219x100.png/ff4444/ffffff', 'Sauce - Thousand Island');
insert into Product (bar_code, description, image, name) values (97935, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/115x100.png/cc0000/ffffff', 'Breadfruit');
insert into Product (bar_code, description, image, name) values (76152, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/207x100.png/cc0000/ffffff', 'Fennel');
insert into Product (bar_code, description, image, name) values (98522, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/107x100.png/dddddd/000000', 'Table Cloth 62x120 White');
insert into Product (bar_code, description, image, name) values (62104, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/118x100.png/dddddd/000000', 'Water - Aquafina Vitamin');
insert into Product (bar_code, description, image, name) values (41982, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/230x100.png/ff4444/ffffff', 'Wine - Acient Coast Caberne');
insert into Product (bar_code, description, image, name) values (87205, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/231x100.png/ff4444/ffffff', 'Pears - Fiorelle');
insert into Product (bar_code, description, image, name) values (97780, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/223x100.png/5fa2dd/ffffff', 'Nantucket Cranberry Juice');
insert into Product (bar_code, description, image, name) values (82990, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/193x100.png/5fa2dd/ffffff', 'Wine - Ice Wine');
insert into Product (bar_code, description, image, name) values (40614, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/187x100.png/cc0000/ffffff', 'Appetizer - Spring Roll, Veg');
insert into Product (bar_code, description, image, name) values (78566, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/137x100.png/dddddd/000000', 'Wine - Two Oceans Cabernet');
insert into Product (bar_code, description, image, name) values (92126, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/220x100.png/cc0000/ffffff', 'Bacardi Raspberry');
insert into Product (bar_code, description, image, name) values (98299, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/215x100.png/cc0000/ffffff', 'Glass - Wine, Plastic, Clear 5 Oz');
insert into Product (bar_code, description, image, name) values (81429, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/221x100.png/5fa2dd/ffffff', 'Flour - Pastry');
insert into Product (bar_code, description, image, name) values (43331, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/167x100.png/5fa2dd/ffffff', 'Mudslide');
insert into Product (bar_code, description, image, name) values (79292, 'Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis!Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.Pra lá , depois divoltis porris, paradis.Sapien in monti palavris qui num significa nadis i pareci latim.', 'http://dummyimage.com/228x100.png/ff4444/ffffff', 'Tart Shells - Sweet, 3');


insert into Stocks (productid, quantity, storeid, unit_price) values (1, 61, 4, 146.43);
insert into Stocks (productid, quantity, storeid, unit_price) values (2, 82, 95, 36.55);
insert into Stocks (productid, quantity, storeid, unit_price) values (3, 27, 29, 267.32);
insert into Stocks (productid, quantity, storeid, unit_price) values (4, 55, 79, 676.98);
insert into Stocks (productid, quantity, storeid, unit_price) values (5, 93, 47, 256.18);
insert into Stocks (productid, quantity, storeid, unit_price) values (6, 43, 57, 732.54);
insert into Stocks (productid, quantity, storeid, unit_price) values (7, 48, 42, 197.81);
insert into Stocks (productid, quantity, storeid, unit_price) values (8, 38, 56, 481.25);
insert into Stocks (productid, quantity, storeid, unit_price) values (9, 69, 5, 311.54);
insert into Stocks (productid, quantity, storeid, unit_price) values (10, 65, 3, 874.48);
insert into Stocks (productid, quantity, storeid, unit_price) values (11, 22, 84, 99.96);
insert into Stocks (productid, quantity, storeid, unit_price) values (12, 22, 25, 679.21);
insert into Stocks (productid, quantity, storeid, unit_price) values (13, 15, 68, 336.75);
insert into Stocks (productid, quantity, storeid, unit_price) values (14, 49, 37, 898.82);
insert into Stocks (productid, quantity, storeid, unit_price) values (15, 71, 72, 725.49);
insert into Stocks (productid, quantity, storeid, unit_price) values (16, 32, 60, 412.83);
insert into Stocks (productid, quantity, storeid, unit_price) values (17, 26, 89, 166.61);
insert into Stocks (productid, quantity, storeid, unit_price) values (18, 28, 80, 663.92);
insert into Stocks (productid, quantity, storeid, unit_price) values (19, 90, 79, 788.55);
insert into Stocks (productid, quantity, storeid, unit_price) values (20, 53, 100, 549.63);
insert into Stocks (productid, quantity, storeid, unit_price) values (21, 2, 78, 179.86);
insert into Stocks (productid, quantity, storeid, unit_price) values (22, 91, 79, 198.88);
insert into Stocks (productid, quantity, storeid, unit_price) values (23, 64, 85, 713.44);
insert into Stocks (productid, quantity, storeid, unit_price) values (24, 82, 20, 342.85);
insert into Stocks (productid, quantity, storeid, unit_price) values (25, 74, 38, 450.05);
insert into Stocks (productid, quantity, storeid, unit_price) values (26, 93, 22, 856.28);
insert into Stocks (productid, quantity, storeid, unit_price) values (27, 11, 76, 263.57);
insert into Stocks (productid, quantity, storeid, unit_price) values (28, 27, 68, 181.71);
insert into Stocks (productid, quantity, storeid, unit_price) values (29, 19, 15, 796.67);
insert into Stocks (productid, quantity, storeid, unit_price) values (30, 95, 41, 255.86);
insert into Stocks (productid, quantity, storeid, unit_price) values (31, 58, 35, 857.34);
insert into Stocks (productid, quantity, storeid, unit_price) values (32, 37, 76, 788.01);
insert into Stocks (productid, quantity, storeid, unit_price) values (33, 64, 92, 787.94);
insert into Stocks (productid, quantity, storeid, unit_price) values (34, 22, 78, 134.83);
insert into Stocks (productid, quantity, storeid, unit_price) values (35, 98, 23, 445.06);
insert into Stocks (productid, quantity, storeid, unit_price) values (36, 61, 5, 35.83);
insert into Stocks (productid, quantity, storeid, unit_price) values (37, 72, 16, 994.79);
insert into Stocks (productid, quantity, storeid, unit_price) values (38, 20, 38, 571.44);
insert into Stocks (productid, quantity, storeid, unit_price) values (39, 68, 39, 130.72);
insert into Stocks (productid, quantity, storeid, unit_price) values (40, 3, 51, 713.87);
insert into Stocks (productid, quantity, storeid, unit_price) values (41, 15, 62, 450.58);
insert into Stocks (productid, quantity, storeid, unit_price) values (42, 26, 45, 397.72);
insert into Stocks (productid, quantity, storeid, unit_price) values (43, 29, 1, 463.69);
insert into Stocks (productid, quantity, storeid, unit_price) values (44, 55, 58, 714.34);
insert into Stocks (productid, quantity, storeid, unit_price) values (45, 45, 13, 399.42);
insert into Stocks (productid, quantity, storeid, unit_price) values (46, 37, 14, 796.02);
insert into Stocks (productid, quantity, storeid, unit_price) values (47, 67, 99, 370.08);
insert into Stocks (productid, quantity, storeid, unit_price) values (48, 57, 22, 509.48);
insert into Stocks (productid, quantity, storeid, unit_price) values (49, 2, 46, 792.88);
insert into Stocks (productid, quantity, storeid, unit_price) values (50, 83, 78, 488.02);
insert into Stocks (productid, quantity, storeid, unit_price) values (51, 27, 47, 200.04);
insert into Stocks (productid, quantity, storeid, unit_price) values (52, 43, 34, 712.24);
insert into Stocks (productid, quantity, storeid, unit_price) values (53, 72, 65, 500.72);
insert into Stocks (productid, quantity, storeid, unit_price) values (54, 81, 33, 507.2);
insert into Stocks (productid, quantity, storeid, unit_price) values (55, 59, 98, 741.36);
insert into Stocks (productid, quantity, storeid, unit_price) values (56, 49, 88, 449.07);
insert into Stocks (productid, quantity, storeid, unit_price) values (57, 43, 40, 256.19);
insert into Stocks (productid, quantity, storeid, unit_price) values (58, 41, 30, 64.89);
insert into Stocks (productid, quantity, storeid, unit_price) values (59, 37, 61, 164.26);
insert into Stocks (productid, quantity, storeid, unit_price) values (60, 29, 37, 259.44);
insert into Stocks (productid, quantity, storeid, unit_price) values (61, 37, 47, 941.54);
insert into Stocks (productid, quantity, storeid, unit_price) values (62, 71, 90, 560.13);
insert into Stocks (productid, quantity, storeid, unit_price) values (63, 60, 56, 556.5);
insert into Stocks (productid, quantity, storeid, unit_price) values (64, 99, 53, 463.45);
insert into Stocks (productid, quantity, storeid, unit_price) values (65, 52, 88, 401.92);
insert into Stocks (productid, quantity, storeid, unit_price) values (66, 57, 7, 187.9);
insert into Stocks (productid, quantity, storeid, unit_price) values (67, 16, 37, 322.96);
insert into Stocks (productid, quantity, storeid, unit_price) values (68, 93, 100, 873.09);
insert into Stocks (productid, quantity, storeid, unit_price) values (69, 32, 14, 429.54);
insert into Stocks (productid, quantity, storeid, unit_price) values (70, 99, 76, 900.99);
insert into Stocks (productid, quantity, storeid, unit_price) values (71, 60, 48, 765.23);
insert into Stocks (productid, quantity, storeid, unit_price) values (72, 96, 8, 317.34);
insert into Stocks (productid, quantity, storeid, unit_price) values (73, 7, 61, 46.91);
insert into Stocks (productid, quantity, storeid, unit_price) values (74, 55, 68, 593.47);
insert into Stocks (productid, quantity, storeid, unit_price) values (75, 8, 52, 631.9);
insert into Stocks (productid, quantity, storeid, unit_price) values (76, 76, 55, 373.74);
insert into Stocks (productid, quantity, storeid, unit_price) values (77, 4, 31, 323.1);
insert into Stocks (productid, quantity, storeid, unit_price) values (78, 6, 33, 974.2);
insert into Stocks (productid, quantity, storeid, unit_price) values (79, 42, 74, 623.57);
insert into Stocks (productid, quantity, storeid, unit_price) values (80, 97, 26, 231.32);
insert into Stocks (productid, quantity, storeid, unit_price) values (81, 48, 76, 933.76);
insert into Stocks (productid, quantity, storeid, unit_price) values (82, 35, 81, 201.85);
insert into Stocks (productid, quantity, storeid, unit_price) values (83, 23, 97, 966.64);
insert into Stocks (productid, quantity, storeid, unit_price) values (84, 18, 40, 219.55);
insert into Stocks (productid, quantity, storeid, unit_price) values (85, 30, 13, 918.48);
insert into Stocks (productid, quantity, storeid, unit_price) values (86, 26, 52, 996.67);
insert into Stocks (productid, quantity, storeid, unit_price) values (87, 36, 34, 32.48);
insert into Stocks (productid, quantity, storeid, unit_price) values (88, 47, 17, 237.18);
insert into Stocks (productid, quantity, storeid, unit_price) values (89, 14, 72, 704.92);
insert into Stocks (productid, quantity, storeid, unit_price) values (90, 44, 12, 601.97);
insert into Stocks (productid, quantity, storeid, unit_price) values (91, 6, 73, 250.55);
insert into Stocks (productid, quantity, storeid, unit_price) values (92, 60, 29, 283.74);
insert into Stocks (productid, quantity, storeid, unit_price) values (93, 3, 7, 686.87);
insert into Stocks (productid, quantity, storeid, unit_price) values (94, 70, 9, 342.89);
insert into Stocks (productid, quantity, storeid, unit_price) values (95, 44, 64, 228.73);
insert into Stocks (productid, quantity, storeid, unit_price) values (96, 61, 75, 500.58);
insert into Stocks (productid, quantity, storeid, unit_price) values (97, 62, 92, 154.44);
insert into Stocks (productid, quantity, storeid, unit_price) values (98, 31, 24, 627.93);
insert into Stocks (productid, quantity, storeid, unit_price) values (99, 44, 72, 877.34);
insert into Stocks (productid, quantity, storeid, unit_price) values (100, 19, 5, 327.87);